global:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 473
    runAsGroup: 473
    fsGroup: 473

alloy:
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
